# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
#  push:
#    branches:
#    - master
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          # Defaults to the user or organization that owns the workflow file
          scope: '@kartverket'

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies and build
        run: npm install && npm run build
      - name: Bump package.json
        run: npm version ${{ steps.tag_version.outputs.new_version }} --no-git-tag-version
        working-directory: static/css
      - name: Publish package on NPM
        run: npm publish
        working-directory: static/css
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
