name: KVIB Package Publish

on:
 # push:
 #   branches:
 #     - master
      
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          # Defaults to the user or organization that owns the workflow file
          scope: '@kartverket'

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

        #   - name: Install dependencies and build
        #      run: npm install && npm run build

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ github.token }}

     # - name: Bump CSS package.json
    #    run: npm version ${{ steps.tag_version.outputs.new_version }} --no-git-tag-version
   #     working-directory: static/css

   #   - name: Publish CSS package on NPM
  #      run: npm publish --access public
 #       working-directory: static/css

      - name: Bump react-components package.json
        run: npm version ${{ steps.tag_version.outputs.new_version }} --no-git-tag-version
        working-directory: static/js/react-components

      - name: Publish react-components package on NPM
        run: npm publish --access public
        working-directory: static/js/react-components

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
